export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';
export const FETCH_SCHEDULE_START = 'FETCH_SCHEDULE_START';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';

export const UPDATE_TIME_ID = 'UPDATE_TIME_ID';
export const INITIALBOOKED_START = 'INITIALBOOKED_START';
export const INITIALBOOKED_ERROR = 'INITIALBOOKED_ERROR';
export const INITIALBOOKED_SUCCESS = 'INITIALBOOKED_SUCCESS';

export const BOOK_ERROR = 'BOOK_ERROR';
export const BOOK_START = 'BOOK_START';
export const BOOK_SUCCESS = 'BOOK_SUCCESS';

export const AUTH_POST_PASS = 'AUTH_POST_PASS';
export const AUTH_POST_FAIL = 'AUTH_POST_FAIL';
export const AUTH_REGISTER = 'AUTH_REGISTER';

export const START_WAIT_SETTING = 'START_WAIT_SETTING';
export const SETTING_POST = 'SETTING_POST';
export const GET_CAR_BY_PORT = 'GET_CAR_BY_PORT';
export const GET_TIMEDEFAULT_BY_PORT = 'GET_TIMEDEFAULT_BY_PORT';

export const VAN_POST = 'VAN_POST';
export const VAN_GET_BY_PORT = 'VAN_GET_BY_PORT';
export const VAN_DELETE = 'VAN_DELETE';

export const GET_COMMENT_BY_PORT = 'GET_COMMENT_BY_PORT';

export const REFESH_STATION = 'REFESH_STATION';

export const CANCLEBOOK_START = 'CANCLEBOOK_START';
export const CANCLEBOOK_SUCCESS = 'CANCLEBOOK_SUCCESS';
export const CANCLEBOOK_ERROR = 'CANCLEBOOK_ERROR';

export const ISCAME_START = 'ISCAME_START';
export const ISCAME_SUCCESS = 'ISCAME_SUCCESS';
export const ISCAME_ERROR = 'ISCAME_ERROR';

export const GET_HISTORY = 'GET_HISTORY';
