export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';
export const FETCH_SCHEDULE_START = 'FETCH_SCHEDULE_START';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';

export const UPDATE_TIME_ID = 'UPDATE_TIME_ID';
export const INITIALBOOKED_START = 'INITIALBOOKED_START';
export const INITIALBOOKED_ERROR = 'INITIALBOOKED_ERROR';
export const INITIALBOOKED_SUCCESS = 'INITIALBOOKED_SUCCESS';

export const BOOK_ERROR = 'BOOK_ERROR';
export const BOOK_START = 'BOOK_START';
export const BOOK_SUCCESS = 'BOOK_SUCCESS';

export const AUTH_POST_PASS = 'AUTH_POST_PASS';
export const AUTH_POST_FAIL = 'AUTH_POST_FAIL';

export const SETTING_POST = 'SETTING_POST';
export const GET_CAR_BY_PORT = 'GET_CAR_BY_PORT';

